### ISSUE TITLE
Class '_ZipStream_\Option\Archive' not found** error when loading Xlsx file

### ISSUE THREAD

**Issue by roel018** [franzholz/base_excel#1]
Hi! I'm getting a **Class '_ZipStream_\Option\Archive' not found** error when loading **Xlsx** file (Xls files are working fine)., I have in fact installed the ZIP extension. This is actually working fine:

var_dump(extension_loaded('zip')); 

...this produces **bool(true)**

The error gets procudes on the following line:

**$options = new Archive();** in the file: _/src/PhpSpreadsheet/Writer/Xlsx.php_

When I use _ZipArchive_ in my extensions myself, however, I always need to use \ZipArchive (with the backslash). Otherwise, it won't function. How can I solve this without needing to adjust all ZipArchive occurences in PhpSpreadSheet to \ZipArchive ? Or does this has to do with something else than ZipArchive? Thanks!

**Comment by franzholz** [comment]
Have a look into the file base_excel/Vendor/PhpSpreadsheet/composer.json .
There you can see the full list of requirements. zipstream is needed for your case. I cannot add it here, because it should come into its own TYPO3 extension. Or you can also add the source code of it manually to your TYPO3 sources.

It is here:  https://github.com/maennchen/ZipStream-PHP   

- "php": "^7.2",
- "ext-ctype": "*",
- "ext-dom": "*",
- "ext-gd": "*",
- "ext-iconv": "*",
- "ext-fileinfo": "*",
- "ext-libxml": "*",
- "ext-mbstring": "*",
- "ext-SimpleXML": "*",
- "ext-xml": "*",
- "ext-xmlreader": "*",
- "ext-xmlwriter": "*",
- "ext-zip": "*",
- "ext-zlib": "*",
- "markbaker/complex": "^1.4",
- "markbaker/matrix": "^1.2",
- "psr/simple-cache": "^1.0",
- "maennchen/zipstream-php": "^2.0"

**Comment by franzholz** [comment]
Use base_excel 0.1.1. This is based on base_zip which brings the ZipStream classes.
